version: "3.8"
services:
  api:
    build: ./apps/api
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./apps/api:/app
    depends_on:
      - db
      - redis
      - minio

  worker:
    build: ./apps/api
    env_file: .env
    command: ["python", "worker.py"]
    volumes:
      - ./apps/api:/app
    depends_on:
      - api
      - db
      - redis
      - minio

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data

volumes:
  pgdata:
  minio:
